-- ============================================================
-- 0003_seed_data.sql
-- Initial catalogue: 8 events + 37 kingdom milestones.
-- ============================================================

INSERT INTO public.events (slug, name, short_name, description, icon_url, guide_route, status, display_order, accent_color)
VALUES
  ('bear-1', 'Bear Hunt 1 — Rally Wave Strategy', 'Bear Hunt 1',
   'How DAD farms the bear with wave-based rallies. 50+ rallies per hunt.',
   '/images/events/bear-hunt.png', '/bear-1', 'active', 10, '#ffd587'),
  ('bear-2', 'Bear Hunt 2', 'Bear Hunt 2',
   'Higher-tier bear with denser rotations. Guide coming.',
   '/images/events/bear-hunt.png', NULL, 'coming-soon', 20, '#ffd587'),
  ('kings-castle', 'King''s Castle Battle', 'King''s Castle',
   'Server-wide castle siege with rotating defenders.',
   '/images/events/kvk.png', NULL, 'coming-soon', 30, '#d44848'),
  ('kvk', 'KvK · Kingdom of Power', 'KvK',
   'Kingdom vs Kingdom — multi-phase: prep, castle battle, brawl, final.',
   '/images/events/kvk.png', NULL, 'coming-soon', 40, '#d44848'),
  ('viking-vengeance', 'Viking Vengeance', 'Viking Vengeance',
   'Viking raid event with score-based rewards.',
   '/images/events/viking-vengeance.png', NULL, 'coming-soon', 50, '#c9883e'),
  ('swordland-showdown', 'Swordland Showdown', 'Swordland Showdown',
   'PvP arena bracket with knockout rounds.',
   '/images/events/swordland-showdown.png', NULL, 'coming-soon', 60, '#6fa8d6'),
  ('tri-alliance-clash', 'Tri-Alliance Clash', 'Tri-Alliance Clash',
   'Three alliances, one trophy. Diplomatic chaos.',
   '/images/events/tri-alliance.png', NULL, 'coming-soon', 70, '#7fc08a'),
  ('cesars-fury', 'Cesar''s Fury', 'Cesar''s Fury',
   'Daily damage rush. Top contributors get the spoils.',
   '/images/events/cesars-fury.png', NULL, 'coming-soon', 80, '#d44848');

INSERT INTO public.kingdom_milestones (slug, name, category, display_order, generation, tg_level, source_url)
VALUES
  ('gen-1-heroes',          'Generation 1 Heroes',          'heroes',      10, 1,   NULL,
   'https://kingshotoptimizer.com/kingdom-timeline/1652'),
  ('first-sanctuary-battle', 'First Sanctuary Battle',       'pvp',         20, NULL, NULL, NULL),
  ('plains-fog-cleared',    'Plains Fog Cleared',           'fog',         30, NULL, NULL, NULL),
  ('mystic-trial-unlocked', 'Mystic Trial Unlocked',        'feature',     40, NULL, NULL, NULL),
  ('first-fortress-battle', 'First Fortress Battle',        'pvp',         50, NULL, NULL, NULL),
  ('fertile-land-fog',      'Fertile Land Fog Cleared',     'fog',         60, NULL, NULL, NULL),
  ('gen-2-heroes',          'Generation 2 Heroes',          'heroes',      70, 2,   NULL,  NULL),
  ('alliance-resource-exchange', 'Alliance Resource Exchange', 'feature', 80, NULL, NULL, NULL),
  ('first-castle-battle',   'First Castle Battle',          'pvp',         90, NULL, NULL, NULL),
  ('gen-1-pets',            'Generation 1 Pets',            'pets',       100, 1,   NULL,  NULL),
  ('age-of-truegold',       'Age of Truegold (TG1-3)',      'truegold',   110, NULL, 3,    NULL),
  ('gen-2-pets',            'Generation 2 Pets',            'pets',       120, 2,   NULL,  NULL),
  ('first-kvk-prep',        'First KvK Prep Starts',        'pvp',        130, NULL, NULL, NULL),
  ('first-kvk-castle',      'First KvK Castle Battle',      'pvp',        140, NULL, NULL, NULL),
  ('first-alliance-brawl',  'First Alliance Brawl',         'pvp',        150, NULL, NULL, NULL),
  ('gen-3-heroes',          'Generation 3 Heroes',          'heroes',     160, 3,   NULL,  NULL),
  ('gen-3-pets',            'Generation 3 Pets',            'pets',       170, 3,   NULL,  NULL),
  ('gov-gear-exchange',     'Gov Gear Material Exchange',   'feature',    180, NULL, NULL, NULL),
  ('masters-unlocked',      'Masters Unlocked (Valora, Pan, Roman)', 'master', 190, NULL, NULL, NULL),
  ('tg5',                   'Truegold 5 (Crucible, T8 Terror)', 'truegold', 200, NULL, 5, NULL),
  ('gov-charm-exchange',    'Gov Charm Material Exchange',  'feature',    210, NULL, NULL, NULL),
  ('master-4',              '4th Master Unlocked (Cassia)', 'master',     220, NULL, NULL, NULL),
  ('charm-cap-raised',      'Governor Charm Cap Raised',    'feature',    230, NULL, NULL, NULL),
  ('gen-4-heroes',          'Generation 4 Heroes (Alcar, Margot, Rosa)', 'heroes', 240, 4, NULL, NULL),
  ('gen-4-pets',            'Generation 4 Pets',            'pets',       250, 4,   NULL,  NULL),
  ('war-academy',           'War Academy Unlocked (T11)',   'war-academy', 260, NULL, NULL, NULL),
  ('gen-5-heroes',          'Generation 5 Heroes (Long Fei, Thrud, Vivian)', 'heroes', 270, 5, NULL, NULL),
  ('gen-5-pets',            'Generation 5 Pets',            'pets',       280, 5,   NULL,  NULL),
  ('tg8',                   'Truegold 8 (Tempered)',        'truegold',   290, NULL, 8,    NULL),
  ('gen-6-heroes',          'Generation 6 Heroes (Triton, Sophia, Yang)', 'heroes', 300, 6, NULL, NULL),
  ('gen-6-pets',            'Generation 6 Pets',            'pets',       310, 6,   NULL,  NULL),
  ('flamedragon-tyrant',    'First Flamedragon Tyrant Battle', 'pvp',     320, NULL, NULL, NULL),
  ('gen-7-heroes',          'Generation 7 Heroes (Charles, Ava, Wee & Woo)', 'heroes', 330, 7, NULL, NULL),
  ('gen-7-pets',            'Generation 7 Pets (Ironclad War Bear)', 'pets', 340, 7, NULL, NULL),
  ('tg10',                  'Truegold 10 (Max)',            'truegold',   350, NULL, 10,   NULL),
  ('gen-8-heroes',          'Generation 8 Heroes',          'heroes',     360, 8,   NULL,  NULL),
  ('gen-8-pets',            'Generation 8 Pets',            'pets',       370, 8,   NULL,  NULL);
